apiVersion: v1
kind: Service
metadata:
  name: name-postgres-service
spec:
  selector:
    app: name-postgres   # must match the label in your Deployment or StatefulSet
  ports:
    - name: postgres
      protocol: TCP
      port: 5432          # service port (inside cluster)
      targetPort: 5432    # container port
  type: ClusterIP

